from pydantic import BaseModel
from typing import Optional
from datetime import datetime

class BookContent(BaseModel):
    """
    Represents the text extracted from Docusaurus-based book websites, 
    including metadata such as source URL, page title, and content segmentation
    """
    id: str
    source_url: str
    page_title: str
    raw_content: str
    created_at: datetime
    updated_at: Optional[datetime] = None


class ContentChunk(BaseModel):
    """
    Segmented portion of book content, prepared for embedding generation
    """
    id: str
    book_content_id: str
    chunk_index: int
    text_content: str
    token_count: int
    created_at: datetime


class EmbeddingVector(BaseModel):
    """
    Semantic representation of text chunks generated by Cohere models, 
    with associated metadata linking back to source content
    """
    id: str
    content_chunk_id: str
    vector: list[float]  # 1024-dimensional embedding vector
    created_at: datetime